app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
]

app/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('home/', views.home, name="home"),
    path('sign-up/', views.sign_up, name="sign_up"),
    path('create-post/', views.create_post, name="create_post"),
    path('edit-post/<int:pk>/', views.edit_post, name="edit_post"),
    path('delete-post/<int:pk>/', views.delete_post, name="delete_post"),
    path('ban-user/<int:ban_user_pk>/', views.ban_user, name="ban_user"),
]

app/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title + "\n" + self.description

app/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Post


class RegisterationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description']

app/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User, Group

from .forms import RegisterationForm, PostForm
from .models import Post


def home(request):
    posts = Post.objects.all()
    return render(request, 'main/home.html', {'posts': posts})


@login_required(login_url='/login')
@permission_required("main.add_post", login_url="/login", raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/home')
    else:
        form = PostForm()

    return render(request, 'main/post.html',
                  {'form': form, 'title': 'Create Post'})


@login_required(login_url='/login')
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk, author=request.user)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.data.get('title')
            post.description = form.data.get('description')
            post.save()
            return redirect('/')
    else:
        form = PostForm(instance=post)

    return render(request, 'main/post.html',
                  {'form': form, 'title': 'Update Post'})


@login_required(login_url='/login')
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author == request.user or request.user.has_perm('main.delete_post'):
        post.delete()
    return redirect('/home')


@login_required(login_url='/login')
def ban_user(request, ban_user_pk):
    user = get_object_or_404(User, pk=ban_user_pk)
    if request.user.is_staff:
        group = Group.objects.filter(name="default").first()
        group.user_set.remove(user)
        group = Group.objects.filter(name="mod").first()
        group.user_set.remove(user)

    return redirect('/home')


def sign_up(request):
    if request.method == "POST":
        form = RegisterationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home/')
    else:
        form = RegisterationForm()

    return render(request, 'registration/sign_up.html', {'form': form})

app/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{% block title %} My Site {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container fluid">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/create-post">Post</a>
                    </li>
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged in as <i class="text-success">{{user.username}}</i> | </span>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

app/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
    <h1 class="py-3">Recent Posts</h1>
    {% for post in posts %}
        <div class="border p-3 mb-2 bg-secondary-subtle">
            <h5>{{post.title}}</h5>
            <p>{{post.description}}</p>
            <hr>
            <div class="d-flex justify-content-between align-items-center">
                <small>{{post.created_at}} by {{post.author.username}}</small>
                {% if perms.main.change_post or perms.main.delete_post %}
                <div>
                    <a href="{% url 'edit_post' post.pk %}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{% url 'delete_post' post.pk %}" class="btn btn-danger btn-sm">Delete</a>
                    {% if user.is_staff %}
                        <a href="{% url 'ban_user' post.author.pk %}" class="btn btn-warning btn-sm">Ban User</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% endblock %}

app/main/templates/main/post.html
{% extends 'main/base.html' %}
{% block title %}
    Post
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <h2 class="py-3">{{title}}</h2>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
{% endblock %}